### ISSUE TITLE
ERROR: Failed requirement 'cpython/3.7.2@bincrafters/stable'

### ISSUE THREAD

**Issue by Prasaddiwalkar** [madebr/conan-cpython#2]
I am facing following when I try to install cpython 
conan install cpython/3.7.2@bincrafters/stable

cpython/3.7.2@bincrafters/stable: Not found in local cache, looking in remotes...
cpython/3.7.2@bincrafters/stable: Trying with 'conan-center'...
cpython/3.7.2@bincrafters/stable: Trying with 'tcapps'...
cpython/3.7.2@bincrafters/stable: Trying with 'bincrafters'...
ERROR: Failed requirement 'cpython/3.7.2@bincrafters/stable' from 'PROJECT'
ERROR: Unable to find 'cpython/3.7.2@bincrafters/stable' in remotes

**Comment by madebr** [comment]
These recipes are up for review for acceptance by the bincrafters project so you'll be unable to download builds from the bincrafters bintray repo (yet).
Additionally, some dependencies are not yet available.

See bincrafters/community#136

PS: cpython has a dependency on cpython_installer, so be sure to build that one first

It would be great if you'd test this recipe and it's dependencies

**Comment by Prasaddiwalkar** [comment]
@madebr Can you please add some more detailed steps to follow.
As well is there any work around to start working on this packages on local machine?

**Comment by madebr** [comment]
Ok

**Comment by madebr** [comment]
First you'll need to clone all recipes of this repo and its dependencies:
```
git clone https://github.com/madebr/conan-flex.git -b tworecipes/2.6.4
git clone https://github.com/madebr/conan-bison.git -b testing/3.3.2
git clone https://github.com/madebr/conan-libdb.git -b testing/5.3.28
git clone https://github.com/madebr/conan-libnsl2.git -b testing/1.2.0
git clone https://github.com/madebr/conan-tk.git -b testing/8.6.9.1
git clone https://github.com/madebr/conan-gdbm.git -b testing/1.18.1
git clone https://github.com/madebr/conan-cpython.git -b testing/3.7.2
```
Then create conan packages in the `bincrafters/stable` user/branch.
```
conan create conan-flex/flex_installer bincrafters/stable
conan create conan-bison/bison_installer bincrafters/stable
conan create conan-libdb bincrafters/stable
conan create conan-libnsl2 bincrafters/stable
conan create conan-tk bincrafters/stable
conan create conan-gdbm bincrafters/stable
conan create conan-cpython/cpython_installer bincrafters/stable
conan create conan-cpython/cpython bincrafters/stable
```

**Comment by Prasaddiwalkar** [comment]
thanks for the steps

%PATH%\cpython>conan create conan-bison/bison_installer bincrafters/stable
Exporting package recipe
bison_installer/3.3.2@bincrafters/stable exports: Copied 1 '.md' file: LICENSE.md
bison_installer/3.3.2@bincrafters/stable exports: Copied 1 '.py' file: bison_common.py
bison_installer/3.3.2@bincrafters/stable: A new conanfile.py version was exported
bison_installer/3.3.2@bincrafters/stable: Folder: C:\Users\deshpapr\.conan\data\bison_installer\3.3.2\bincrafters\stable\export
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

**ERROR: bison_installer/3.3.2@bincrafters/stable: Invalid configuration: Flex is not supported on Windows.**

**Comment by madebr** [comment]
@Prasaddiwalkar 
My conan recipes don't support Windows (yet).
I have only tested them on Linux.

https://github.com/bincrafters/community/issues/136#issuecomment-464752619

**Comment by Prasaddiwalkar** [comment]
@madebr 
The product for which I am trying to use your recipe support multiple platforms, I may need it for windows, Linux, Solaris and HP-UX.
What is your road map to support other platforms?

**Comment by Croydon** [comment]
We do have a Conan recipe for Winflexbison which should help in the flex case

**Comment by madebr** [comment]
See conan-io/conan-center-index#1510
